# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: centos:centos7

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: salhe/yasqlplus
      # - name: Use centos7
      #   uses: docker://centos:7.6.1810
      - name: glibc
        run: ls && ldconfig -v | grep libc.so && ldd --version
      - name: Install wget
        run: yum -y install centos-release-scl && yum install -y wget gcc g++ devtoolset-9-gcc devtoolset-9-gcc-c++ devtoolset-9-binutils
      - name: Install clang
        run: |
          yum install -y centos-release-scl-rh
          yum install -y llvm-toolset-7.0-clang
          echo /opt/rh/llvm-toolset-7.0/root/usr/lib >> /etc/ld.so.conf
          echo /opt/rh/llvm-toolset-7.0/root/usr/lib64 >> /etc/ld.so.conf
          echo LD_LIBRARY_PATH=/opt/rh/llvm-toolset-7.0/root/usr/lib64:$LD_LIBRARY_PATH >> $GITHUB_ENV
          echo source /opt/rh/devtoolset-9/enable >> /etc/profile
      - name: find
        run: find / -name "stddef.h" && yum install -y tree && tree /opt/rh/llvm-*
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Download Dependencies
        run: ./scripts/download-dependency.sh
      - name: Build project
        run: |
          cat /opt/rh/devtoolset-9/enable
          rm /etc/ld.so.cache
          ldconfig
          ldconfig -p
          source /opt/rh/devtoolset-9/enable
          cargo build # --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./target/release/yasqlplus
